#configuração da conta de e-mail
email=ovm.extrator.logs@gmail.com
senha=veaxmyizbdqcnzhx
intervalo_minutos=1

#IP dos PDVs
PDV_192=10.56.90.31
PDV_196=10.56.90.27
PDV_503=10.56.90.26
PDV_450=10.56.90.14
PDV_451=10.56.90.29
PDV_458=10.56.90.18
PDV_380=10.56.90.24
PDV_53=10.56.90.11
PDV_580=10.56.90.28
PDV_CX012TH05=10.61.24.5
PDV_CX012TH06=10.61.24.6

#Caminho e nome dos arquivos de log
CSIDebugFile=\p2k\bin\CSIDebugFile.txt
CSIDebugFileRT=\p2k\bin\CSIDebugFileRT.txt
CSIDebugFileSO=\p2k\bin\CSIDebugFileSO.txt
comunicacao_ws=\p2k\bin\logger\comunicacao-ws\integrador_comunicacao_ws.log
integrador_idb_client=\p2k\bin\logger\integrador_idb_client\linx-adeo-idb-client.log
integrador_nfeio_client=\p2k\bin\logger\integrador_nfeio_client\linx-nfeio-client.log
loyalty_client=\p2k\bin\logger\coletadados\linx-data-capture-loyalty-client.log
MFDE=\p2k\bin\MFDE\
Mid-e=\p2k\bin\log\mid-e-core.log



