#credenciais de acesso remoto aos PDVs (usuario e senha do Windows com acesso admin compartilhado)
windows_user=lmbr\caissehmlp2k
windows_senha=tkx31Na9

#configuração da conta de e-mail
email=ovm.extrator.logs@gmail.com
senha=webnwminnrvjafic
intervalo_minutos=1

#IP dos PDVs
PDV_192=10.56.90.31
PDV_194=10.56.90.24
PDV_196=10.56.90.27
PDV_198=10.56.90.20
PDV_503=10.56.90.26
PDV_504=10.56.90.30
PDV_450=10.56.90.14
PDV_451=10.56.90.29
PDV_458=10.56.90.18
PDV_380=10.56.90.41
PDV_53=10.56.90.11
PDV_277=10.56.90.10
PDV_580=10.56.90.28
PDV_CX012TH05=10.61.24.5
PDV_CX012TH06=10.61.24.6

#Caminho e nome dos arquivos de log
CSIDebugFile=\p2k\bin\CSIDebugFile.txt
CSIDebugFileRT=\p2k\bin\CSIDebugFileRT.txt
CSIDebugFileSO=\p2k\bin\CSIDebugFileSO.txt
comunicacao_ws=\p2k\bin\logger\comunicacao-ws\linx-comunicacao-ws.log
integrador_idb_client=\p2k\bin\logger\integrador_idb_client\linx-adeo-idb-client.log
integrador_nfeio_client=\p2k\bin\logger\integrador_nfeio_client\linx-nfeio-client.log
loyalty_client=\p2k\bin\logger\coletadados\linx-data-capture-loyalty-client.log
MFDE=\p2k\bin\MFDE\
Mid-e=\p2k\bin\log\mid-e-core.log
promo-client=\p2k\Bin\log\linx-promo-client.log
linx-tef=\p2k\Bin\logger\tef\linx-tef.log

#Parametros para Parametrizacao PDV
#Formato: <nome_parametro>.arquivo / .constante / .valor
parametrosGeraisPDV.properties.arquivo=\p2k\bin\parametrosGeraisPDV.properties
parametrosGeraisPDV.properties.constante=PARAM_NFCE_TIPO_AMBIENTE
parametrosGeraisPDV.properties.valor=2

# ext.properties
ext.properties.arquivo=\p2k\ext\ext.properties
ext.properties.constante=tef
ext.properties.valor=/p2k/ext/tef/softwareexpress/7.0.117.61.r4_s

#serv-config-comunicacao.dat
serv-config-comunicacao.dat.arquivo=\p2k\config\serv-config-comunicacao.dat
serv-config-comunicacao.dat.valor=10.56.62.140:4057

# END_SRV_MON
end_srv_mon.arquivo=\p2k\bin\parametrosGeraisSeguranca.properties
end_srv_mon.constante=END_SRV_MON
end_srv_mon.valor=6e0701618ceb161a163bff17bcdae9041cda546f25c3642762ef703719dc5ef165ed9db6c17c4fe71ca9757b0dbb8bba380820bdb98f81a4ae24ae8fa488be948db16261b61fb4f5df5c8ba428b7468b7d970482d2fa9e4270f00c9ecc28f870e142c62ed8919b8fb80504814bcd46b94ca35747999eda730736feb015cb0fdf

#upload.senha
upload.senha.arquivo=\p2k\bin\parametrosGeraisSeguranca.properties
upload.senha.constante=upload.senha
upload.senha.valor=8ce31cf85c57fbc4bd935f94b2c84f24dc00ffdef59ef56a293479681ca7555f620c49ef3dba2a995f70a4e2e34468b7424ac2ea6017c0a080d36229c7edfb2854ee7daa0c0800ee95b25c38ab708eefa7b24d3f7c6a7a8762d80ed07b2dd0108644dcccdbf3477acbc8a23ad3d1a3873f192b6ae181ba12fd910c367540e3f8